### ISSUE TITLE
Customer cannot be attached in orders

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#113] opened 2020-12-03 04:55 UTC
-After login to app, go to burger menu>Orders. 
-click edit on any order. 
-Click select Customer. 
-Select any customer from choices offered. 

Observed. It does not get added to the order. The field remains empty.

**Comment by harsimranmaan** [comment] 2020-12-03 04:58
I think this might be a duplicate of #80

**Comment by harsimranmaan** [comment] 2020-12-03 04:59
The field is assigned but the user has not visual indication

**Comment by harsimranmaan** [comment] 2020-12-07 06:23
I think this is a case of customer case not shown on the order list page.

**Comment by schima** [comment] 2020-12-07 21:22
Thanks. looking forward to getting this fixed in newer version

**Closed** 2020-12-08 07:20 UTC
Labels: bug
