### ISSUE TITLE
No validation on number of characters in subject line.

### ISSUE THREAD

**Issue by schima** [bigpanther/shipanther#246] opened 2021-01-08 02:40 UTC
-Create new artifact and in the name, there is no limit of how many letters can be added. 
-When attempted to save, it generates error 500. 

See attachment. ![image](https://user-images.githubusercontent.com/20378193/103967927-d84db100-5117-11eb-8a9d-26335e0cdce0.png)

**Comment by harsimranmaan** [comment] 2021-01-18 07:37
Duplicate of #144

**Closed by harsimranmaan** 2021-01-18 07:37 UTC
Labels: bug
